# Generated by Django 2.2.6 on 2019-10-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191013_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calorie_counter',
            name='cal_amount',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.IntegerField(blank=True),
        ),
    ]
