# Generated by Django 2.2.6 on 2019-10-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191013_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calorie_counter',
            name='cal_amount',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
