# Generated by Django 2.2.5 on 2019-10-15 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_exercise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='onerm',
            new_name='one_rep_max',
        ),
    ]
