# Generated by Django 2.2.6 on 2019-10-17 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_skullcrushers_tricep_extension'),
        ('users', '0018_hip_thrust'),
    ]

    operations = [
    ]
